### ISSUE TITLE
We Need to Choose a Simple Game to Build

### ISSUE THREAD

**Issue by blakeroy01** [blakeroy01/smog#5]
I really like the idea of building a two-player snake game with custom defined rules.

For example, the flow could look like this:
```
Two nodes will access the game through browser

Both nodes will be placed in a lobby and displayed a message: First to 5 apples wins. If you run into yourself or the opponent, you lose.

Game starts, and the sockets communicate between the client and server.
```

Here's a PyGame Tutorial to a basic Snake implementation: https://www.youtube.com/watch?v=8dfePlONtls

**Comment by connorwalsh21** [comment]
I like the idea of a super simple snake game. Would work very well as an iMessage game. Something that you can easily play with many people without a whole download.
